- hosts: master
  become: true
  tasks:
# The script create a mongo-admin root user in the db admin
  - name: Copy createDB user script to docker host
    copy:
      src: files/
      dest: /tmp/script

  - name: Create mongo-admin user in MongoDB
    shell: >
      sudo docker exec -i mongo sh -c
      "mongo < /home/script/createDB.js"

# The mongo-admin users are kept inside the persistance volume storage,
# We can recreate the docker container this round with replication tag
# The reason we have to use this method because the mongo docker Image
# doesn't use the config file

  - name: Recreate mongodb master container with replSet tags
    docker_container:
      name: mongo
      image: mongo:3.4-jessie
      recreate: yes
      state: started
      command:
        - "--replSet \"rs0\""
        - "--bind_ip 0.0.0.0"
      volumes:
        - "mongo_log:/var/log/"
        - "mongo_data:/data/db"
        - "/tmp/script:/home/script:z"
      ports:
        - "27017:27017"

# Init the cluster with two secondary is db1.test.com and db2.test.com

  - name: init the cluster
    shell: >
      sudo docker exec -i mongo sh -c
      "mongo -u mongo-admin -p password --authenticationDatabase admin < /home/script/rsinit.js"
